## Define cards
names = [
    "Anthropos",
    "Demiurge",
    "Astaroth",
    "Kether - Hierarchy",
    "Chokmah - Submission",
    "Binah - Community",
    "Chesed - Safety",
    "Geburah - Law",
    "Tiphareth - Allure",
    "Netzach - Victory",
    "Hod - Honor",
    "Yesod - Avarice",
    "Malkuth - Awakening",
    "Thaumiel - Power",
    "Chagidiel - Abuse",
    "Sathariel - Exclusion",
    "Gamichicoth - Fear",
    "Golab - Torment",
    "Togarini - Compulsion",
    "Hareb-Serap - Conflict",
    "Samael - Vengeance",
    "Gamaliel - Lust",
    "Nahemoth - Discord",
    "One of Skulls - Metropolis",
    "Two of Skulls - Forgetfulness",
    "Three of Skulls - Remnants",
    "Four of Skulls - Spirit",
    "Five of Skulls - Transition",
    "Six of Skulls - Flesh",
    "Seven of Skulls - Weapon",
    "Eight of Skulls - Suffering",
    "Nine of Skulls - Inferno",
    "One of Roses - Gaia",
    "Two of Roses - Birth",
    "Three of Roses - Survival",
    "Four of Roses - Growth",
    "Five of Roses - Predator",
    "Six of Roses - Swarm",
    "Seven of Roses - Prey",
    "Eight of Roses - Obsession",
    "Nine of Roses - Love",
    "One of Hourglasses - Achlys",
    "Two of Hourglasses - Future",
    "Three of Hourglasses - Past",
    "Four of Hourglasses - Space",
    "Five of Hourglasses - Borderland",
    "Six of Hourglasses - Hidden",
    "Seven of Hourglasses - Labyrinth",
    "Eight of Hourglasses - Crossroad",
    "Nine of Hourglasses - Gate",
    "One of Crescents - Vortex",
    "Two of Crescents - Creation",
    "Three of Crescents - Undoing",
    "Four of Crescents - Transformation",
    "Five of Crescents - Connection",
    "Six of Crescents - Merging",
    "Seven of Crescents - Reflection",
    "Eight of Crescents - Repetition",
    "Nine of Crescents - Stillness",
    "One of Eyes - Elysium",
    "Two of Eyes - Imprisonment",
    "Three of Eyes - Faith",
    "Four of Eyes - Distractions",
    "Five of Eyes - Division",
    "Six of Eyes - Rebellion",
    "Seven of Eyes - Madness",
    "Eight of Eyes - Visions",
    "Nine of Eyes - Enlightenment",
]

major_arcana = names[:23]
minor_arcana = names[23:]

ind = [
    "# Individual",
    "Card 1: A core Characteristic of the individual.",
    "Card 2: Something from the Past that shaped the individual.",
    "Card 3: An Ambition that drives the individual.",
    "Card 4: The individual’s greatest Weakness.",
    "Card 5: The individual’s greatest Strength.",
]

loc = [
    "# Location",
    "Card 1: The Type of location.",
    "Card 2: Something about the location’s Past.",
    "Card 3: An unexpected or quirky Trait.",
    "Card 4: A Weakness at the location, which might be exploited.",
    "Card 5: Something that makes the location Exceptional.",
]

cul = [
    "# Cult",
    "Card 1: What Power/Ambition Drives the cult?",
    "Card 2: An important thing about the cult’s History.",
    "Card 3: What does the cult wish to Accomplish?",
    "Card 4: What is the cult’s Weakness, such as enemies?",
    "Card 5: What is the cult’s unexpected Resource?",
]

plo = [
    "# Plot",
    "Card 1: What is the Power behind the plot?",
    "Card 2: What Caused the plot?",
    "Card 3: What is the Next Move in the plot?",
    "Card 4: What power Opposes the plot?",
    "Card 5: What power Supports the plot?",
]

cre = [
    "# Creature",
    "Card 1: From what background does the creature Originate?",
    "Card 2: From where can you find Information about the creature?",
    "Card 3: What Drives the creature?",
    "Card 4: What is the creature’s Weakness?",
    "Card 5: What is the creature’s Strength?",
]

art = [
    "# Artifact",
    "Card 1: From where does the Artifact Originate?",
    "Card 2: Who else is Looking for It?",
    "Card 3: What are the Dangers in using it?",
    "Card 4: What is its Primary Power?",
    "Card 5: What is its Secondary Power?",
]
